apiVersion: 1
deleteDatasources:
- name: Prometheus
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus.default.svc.cluster.local
  isDefault: true
  version: 1
  editable: true
- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://influxdb.default.svc.cluster.local
  user: reader
  password: YNrZB8HKcUWj7
  database: jenkins
  jsonData:
    httpMode: GET
