apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
    role: db
    component: ci-glance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      role: db
      component: ci-glance
  template:
    metadata:
      labels:
        app: prometheus
        role: db
        component: ci-glance
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.9.2
        ports:
        - name: http
          containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
      volumes:
      - name: config
        configMap:
          name: prometheus
          items:
          - key: prometheus.yaml
            path: prometheus.yml
