apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    role: db
    component: ci-glance
spec:
  selector:
    app: prometheus
    role: db
    component: ci-glance
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9090
