global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: jenkins
    scheme: http
    metrics_path: /prometheus
    static_configs:
      - targets: ["jenkins.default.svc.cluster.local"]
