apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
    role: db
    component: ci-glance
spec:
  selector:
    app: mariadb
    role: db
    component: ci-glance
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
