apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
    role: db
    component: ci-glance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
      role: db
      component: ci-glance
  template:
    metadata:
      labels:
        app: influxdb
        role: db
        component: ci-glance
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.7.6
        ports:
        - name: api
          containerPort: 8086
          protocol: TCP
        env:
        - name: INFLUXDB_DB
          value: jenkins
        - name: INFLUXDB_HTTP_AUTH_ENABLED
          value: "true"
        - name: INFLUXDB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: influxdb
              key: INFLUXDB_ADMIN_USER
        - name: INFLUXDB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb
              key: INFLUXDB_ADMIN_PASSWORD
        - name: INFLUXDB_USER
          valueFrom:
            secretKeyRef:
              name: influxdb
              key: INFLUXDB_USER
        - name: INFLUXDB_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb
              key: INFLUXDB_USER_PASSWORD
        - name: INFLUXDB_READ_USER
          valueFrom:
            secretKeyRef:
              name: influxdb
              key: INFLUXDB_READ_USER
        - name: INFLUXDB_READ_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb
              key: INFLUXDB_READ_USER_PASSWORD
        - name: INFLUXDB_WRITE_USER
          valueFrom:
            secretKeyRef:
              name: influxdb
              key: INFLUXDB_WRITE_USER
        - name: INFLUXDB_WRITE_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb
              key: INFLUXDB_WRITE_USER_PASSWORD
