apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
    role: db
    component: ci-glance
spec:
  selector:
    app: influxdb
    role: db
    component: ci-glance
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: 8086
